### ISSUE TITLE
QR Eigenvalue Solver

### ISSUE THREAD

**Issue by fnueske** [markovmodel/variational#27]
@fabian-paul  and I have started to implement our own version of the eigenvalue solver to circumvent stability issues we have observed some time ago. It can be found as a cython module under /variational/solvers/qr_c/
@marscher : Could you check out the QR_Eigenvalue_Solver branch and have a look at the setup? The new module is not available if we use python setup.py install, however, it is available if we use develop instead. Also, there are a lot of warnings while the .pyx-file is compiled. 

The method itself seems to work correctly.

**Comment by marscher** [comment]
I can not reproduce the different behaviour of install vs develop mode locally nor do I observe warnings (there are a lot of warnings in covartools due to datatype truncation) during the compilation of your extension.

The extension code is super clean. Thank you for introducing this numpy.require pointer assignment notation - it is very readable.

Can you try updating setuptools and cython locally?
